#!/bin/bash

set -e

SCRIPT_DIR=$(dirname `readlink -f $0`)
PROJECT_DIR=$(readlink -f $SCRIPT_DIR/../../)
if [ "$PROJECT_DIR" = "/" ]; then
  PROJECT_DIR="/pomodoro.cc"
fi

ENV="$1"

docker run --name pomodoro-auth \
  --restart=always \
  --detach=true \
  --env ENV="$ENV" \
  --volume $PROJECT_DIR/credentials.json:/credentials.json \
  --link pomodoro-auth-sessions:pomodoro-auth-sessions \
  --link pomodoro-auth-db:pomodoro-auth-db \
  christianfei/pomodoro-auth
