#!/bin/bash

set -e

SCRIPT_DIR=$(dirname `readlink -f $0`)
PROJECT_DIR=$(readlink -f $SCRIPT_DIR/../../)
if [ "$PROJECT_DIR" = "/" ]; then
  PROJECT_DIR="/pomodoro.cc"
fi

id_for_container(){
  CONTAINER="$1\s*$"
  CONTAINER_ID="$(docker ps -a | grep "$CONTAINER" | awk '{print $1}')"
  echo $CONTAINER_ID
}

if [ ! -z "$(id_for_container 'pomodoro-auth-test')" ]; then
  docker rm -f pomodoro-auth-test
fi
if [ ! -z "$(id_for_container 'pomodoro-auth-db-test')" ]; then
  docker rm -f pomodoro-auth-db-test
fi
if [ ! -z "$(id_for_container 'pomodoro-auth-sessions-test')" ]; then
  docker rm -f pomodoro-auth-sessions-test
fi

docker run --name pomodoro-auth-db-test -d mongo:latest

docker run --name pomodoro-auth-sessions-test -d smebberson/alpine-redis redis-server

docker run -it \
  --name pomodoro-auth-test \
  --link=pomodoro-auth-db-test:pomodoro-auth-db \
  --link=pomodoro-auth-sessions-test:pomodoro-auth-sessions \
  --env ENV="DEV" \
  -v $PROJECT_DIR/credentials.json:/credentials.json \
  -v $PROJECT_DIR/auth:/app \
  christianfei/pomodoro-auth sh -c 'npm test'

TEST_RESULT_CODE=$?

docker rm -f pomodoro-auth-test
docker rm -f pomodoro-auth-sessions-test
docker rm -f pomodoro-auth-db-test

exit $TEST_RESULT_CODE
