#!/bin/bash

set -e

env

echo "RUN pomodoro-api-db"

docker run --name pomodoro-api-db \
  --restart=always \
  --volume /db_v2:/var/lib/postgresql/data \
  -d postgres

  # -e POSTGRES_PASSWORD=postgres \