#!/bin/bash

set -e

SCRIPT_DIR=$(dirname `readlink -f $0`)
PROJECT_DIR=$(readlink -f $SCRIPT_DIR/../../)
if [ "$PROJECT_DIR" = "/" ]; then
  PROJECT_DIR="/pomodoro.cc"
fi

ENV="$1"

VOLUME=""
if [ "$ENV" = "DEV" ]; then
  VOLUME="--volume $PROJECT_DIR/docs/build:/usr/html/"
fi
docker run --name pomodoro-docs \
  --restart=always \
  --detach=true \
  $VOLUME \
  christianfei/pomodoro-docs
