#!/bin/bash

set -e

SCRIPT_DIR=$(dirname `readlink -f $0`)
PROJECT_DIR=$(readlink -f $SCRIPT_DIR/../../)
if [ "$PROJECT_DIR" = "/" ]; then
  PROJECT_DIR="/pomodoro.cc"
fi

id_for_container(){
  CONTAINER="$1\s*$"
  CONTAINER_ID="$(docker ps -a | grep "$CONTAINER" | awk '{print $1}')"
  echo $CONTAINER_ID
}

docker run --name pomodoro-api-db-test --detach=true mongo:latest

docker run --name pomodoro-api-sessions-test --detach=true redis:latest redis-server

docker run --name pomodoro-api-test \
  --detach=true \
  --volume $PROJECT_DIR/credentials.json:/credentials.json \
  --volume $PROJECT_DIR/shared:/shared \
  --link pomodoro-api-sessions-test:pomodoro-api-sessions \
  --link pomodoro-api-db-test:pomodoro-api-db \
  christianfei/pomodoro-api


TEST_COMMAND="mix test"

if [ "$TRAVIS" == "true" ]; then
  TEST_COMMAND="mix deps.get; $TEST_COMMAND"
fi

env
echo "--> executing: $TEST_COMMAND"

docker run --rm \
  --name pomodoro-api_v2-test \
  --env MIX_ENV="test" \
  --link pomodoro-api-test:pomodoro-api \
  --volume $PROJECT_DIR/api_v2:/app \
  christianfei/pomodoro-api_v2 sh -c "$TEST_COMMAND"

TEST_RESULT_CODE=$?

docker rm -f pomodoro-api-test
docker rm -f pomodoro-api-db-test
docker rm -f pomodoro-api-sessions-test

exit $TEST_RESULT_CODE
