#!/bin/bash

set -e

SCRIPT_DIR=$(dirname `readlink -f $0`)
PROJECT_DIR=$(readlink -f $SCRIPT_DIR/../../)
if [ "$PROJECT_DIR" = "/" ]; then
  PROJECT_DIR="/pomodoro.cc"
fi

id_for_container(){
  CONTAINER="$1\s*$"
  CONTAINER_ID="$(docker ps -a | grep "$CONTAINER" | awk '{print $1}')"
  echo $CONTAINER_ID
}

docker run --rm \
  --name pomodoro-api_v2-test \
  --env MIX_ENV="test" \
  -v $PROJECT_DIR/api_v2:/app \
  christianfei/pomodoro-api_v2 sh -c 'mix test'

TEST_RESULT_CODE=$?

exit $TEST_RESULT_CODE
