#!/bin/bash

set -e

SCRIPT_DIR=$(dirname `readlink -f $0`)
PROJECT_DIR=$(readlink -f $SCRIPT_DIR/../../)
if [ "$PROJECT_DIR" = "/" ]; then
  PROJECT_DIR="/pomodoro.cc"
fi

docker run --name pomodoro-main \
  --restart=always \
  --detach=true \
  --publish 80:80 \
  --publish 443:443 \
  --link pomodoro-app:pomodoro-app \
  --link pomodoro-auth:pomodoro-auth \
  --link pomodoro-api:pomodoro-api \
  --link pomodoro-docs:pomodoro-docs \
  --volume $PROJECT_DIR/main/etc/nginx/nginx.conf:/etc/nginx/nginx.conf \
  christianfei/pomodoro-main
