#!/bin/bash

set -e

#echo "--> installing system dependencies"
#curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
#sudo apt-get install -y nodejs
#sudo apt-get install -y npm

echo "--> installing app dependencies"
(cd app; npm install)

echo "--> installing auth dependencies"
(cd auth; npm install)

echo "--> installing acceptance-tests dependencies"
(cd acceptance-tests; npm install)

echo "--> installing docs dependencies"
(cd docs; npm install)

echo "--> building app"
(cd app; npm run build)

echo "--> building docs"
(cd docs; npm run build)

echo "--> creating credentials.json"
cp credentials.template.json credentials.json

echo "--> creating opt/docker.env"
cp opt/docker.template.env opt/docker.env
