#!/bin/bash

set -e

echo "--> installing global dependencies"
npm install

echo "--> installing app dependencies"
(cd app; npm install)

echo "--> installing api dependencies"
(cd api; npm install)

echo "--> building app"
(cd app; ./node_modules/gulp/bin/gulp.js)

echo "--> creating credentials.json"
cp credentials.template.json credentials.json

echo "--> creating opt/docker.env"
cp opt/docker.template.env opt/docker.env

echo "--> setting up self-signed certificate"
unzip ssl.zip -d .

echo "--> building containers"
opt/docker.build
