#!/bin/bash

set -e

echo "--> installing app dependencies"
(cd app; npm install)

echo "--> installing auth dependencies"
(cd auth; npm install)

echo "--> installing acceptance-tests dependencies"
(cd acceptance-tests; npm install)

echo "--> installing docs dependencies"
(cd docs; npm install)

echo "--> building app"
(cd app; npm run build)

echo "--> creating credentials.json"
cp credentials.template.json credentials.json

echo "--> creating opt/docker.env"
cp opt/docker.template.env opt/docker.env

echo "--> setting up self-signed certificate"
unzip ssl.zip -d . || true
