#!/bin/bash

echo "<== DEPLOY"
ROOT=$(pwd)
echo $ROOT
echo "<== DEPLOY"

echo "--> building app"
PRODUCTION=true app/opt/build

echo "--> building containers"
opt/docker.build

echo "--> logging in to docker hub"
docker login -e "$DOCKER_EMAIL" -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

echo "--> pushing main to docker hub"
docker push christianfei/pomodoro-main
echo "--> pushing app to docker hub"
docker push christianfei/pomodoro-app
echo "--> pushing auth to docker hub"
docker push christianfei/pomodoro-auth
echo "--> pushing api to docker hub"
docker push christianfei/pomodoro-api


if [[ "$TRAVIS" == "true" ]]; then
  echo "--> exiting"
  exit 0
fi


echo "--> server"
echo "--> getting latest changes"
ssh pigeon@pomodoro.cc '/pomodoro.cc/opt/git.fetchclean'

echo "--> pulling and restarting containers"
ssh pigeon@pomodoro.cc '/pomodoro.cc/opt/docker.pullrestart'
